# Generated by Django 3.0.4 on 2020-04-04 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='job',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='workplace',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='worktime',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
