# Generated by Django 3.0.5 on 2020-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200404_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='worktime',
            field=models.CharField(choices=[('FULL', 'Fulltime'), ('PART', 'Parttime'), ('FULLandPART', 'Fulltime and Parttime')], default=None, max_length=255),
        ),
    ]
